<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20170109120622 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE kaystrobach_contact_domain_model_address (persistence_object_identifier VARCHAR(40) NOT NULL, street VARCHAR(255) NOT NULL, housenumber VARCHAR(255) NOT NULL, addressaddon VARCHAR(255) NOT NULL, roomnumber VARCHAR(255) NOT NULL, zipcode VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kaystrobach_contact_domain_model_contact (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(40) DEFAULT NULL, address VARCHAR(40) DEFAULT NULL, position VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, mobile VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_62ADCBD85E237E06 (name), UNIQUE INDEX UNIQ_62ADCBD8D4E6F81 (address), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kaystrobach_contact_domain_model_institution (persistence_object_identifier VARCHAR(40) NOT NULL, address VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_4CC1CA20D4E6F81 (address), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kaystrobach_contact_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, contact VARCHAR(40) DEFAULT NULL, institution VARCHAR(40) DEFAULT NULL, UNIQUE INDEX UNIQ_A32C8B074C62E638 (contact), INDEX IDX_A32C8B073A9F98E5 (institution), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_contact ADD CONSTRAINT FK_62ADCBD85E237E06 FOREIGN KEY (name) REFERENCES typo3_party_domain_model_personname (persistence_object_identifier)');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_contact ADD CONSTRAINT FK_62ADCBD8D4E6F81 FOREIGN KEY (address) REFERENCES kaystrobach_contact_domain_model_address (persistence_object_identifier)');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_institution ADD CONSTRAINT FK_4CC1CA20D4E6F81 FOREIGN KEY (address) REFERENCES kaystrobach_contact_domain_model_address (persistence_object_identifier)');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_user ADD CONSTRAINT FK_A32C8B074C62E638 FOREIGN KEY (contact) REFERENCES kaystrobach_contact_domain_model_contact (persistence_object_identifier)');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_user ADD CONSTRAINT FK_A32C8B073A9F98E5 FOREIGN KEY (institution) REFERENCES kaystrobach_contact_domain_model_institution (persistence_object_identifier)');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_user ADD CONSTRAINT FK_A32C8B0747A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_contact DROP FOREIGN KEY FK_62ADCBD8D4E6F81');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_institution DROP FOREIGN KEY FK_4CC1CA20D4E6F81');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_user DROP FOREIGN KEY FK_A32C8B074C62E638');
        $this->addSql('ALTER TABLE kaystrobach_contact_domain_model_user DROP FOREIGN KEY FK_A32C8B073A9F98E5');
        $this->addSql('DROP TABLE kaystrobach_contact_domain_model_address');
        $this->addSql('DROP TABLE kaystrobach_contact_domain_model_contact');
        $this->addSql('DROP TABLE kaystrobach_contact_domain_model_institution');
        $this->addSql('DROP TABLE kaystrobach_contact_domain_model_user');
    }
}